config/routes.rb
Rails.application.routes.draw do
  resources :booklets
  resources :conferences
  resources :incollections
  resources :manuals
  resources :masterstheses
  resources :miscs
  resources :phdtheses
  resources :proceedings
  resources :techreports
  resources :unpuplisheds
  resources :bibtexes
  resources :inproceedings
  resources :books
  resources :articles
  resources :references

  root 'references#index'

end

app/models/article.rb
class Article < Reference
  validates :author, :journal, :volume, :title, :year, presence: true
end

app/models/bibtex.rb
class Bibtex < ActiveRecord::Base
end

app/models/book.rb
class Book < Reference
  validates :title, :year, :publisher, presence: true
end

app/models/booklet.rb
class Booklet < Reference
  validates :title, presence: true
end

app/models/conference.rb
class Conference < Reference
  validates :title, :year, :author, :booktitle, presence: true
end

app/models/incollection.rb
class Incollection < Reference
  validates :title, :publisher, :year, :author, :booktitle, presence: true
end

app/models/inproceeding.rb
class Inproceeding < Reference
  validates :title, :year, :author, :booktitle, presence: true
end

app/models/manual.rb
class Manual < Reference
  validates :title, presence: true
end

app/models/mastersthesis.rb
class Mastersthesis < Reference
  validates :author, :title, :school, :year, presence: true
end

app/models/misc.rb
class Misc < Reference
end

app/models/phdthesis.rb
class Phdthesis < Reference
  validates :author, :title, :school, :year, presence: true
end

app/models/proceeding.rb
class Proceeding < Reference
  validates :title, :year, presence: true
end

app/models/reference.rb
class Reference < ActiveRecord::Base

  def create_key
    key = self.author.partition(" ").first + self.year.to_s + self.title.partition(" ").first
    references = Reference.all
    abc = "abcdefghijklmnopqrstuvwxyz"
    abcIndex = 0
    while Reference.exists?(key: key)
        if abcIndex > 0 && abcIndex < abc.length
            key = key.chop
        end
        key = key + abc[abcIndex]
        if abcIndex < abc.length
            abcIndex = abcIndex + 1
        else
            abcIndex = 0
        end
    end
    self.key = key
  end

  def serialized_fields
    [:author, :title, :journal, :volume, :number, :month, :year, :pages, :publisher, :editor, :booktitle, :organization, :address, :note, :edition, :series, :annote, :chapter, :crossref, :howpublished, :institution, :school, :type] 
  end

  def to_s
    str = "@#{entry_type}{#{key},\n"
    serialized_fields.each do |field|
      str += "      #{field.to_s} = {#{self[field]}},\n" unless self[field].blank?
    end
    str += "}\n"
  end
end

app/models/techreport.rb
class Techreport < Reference
  validates :author, :title, :institution, :year, presence: true
end

app/models/unpuplished.rb
class Unpuplished < Reference
  validates :author, :title, :note, presence: true
end

app/controllers/bibtexes_controller.rb
class BibtexesController < ApplicationController
  before_action :set_bibtex, only: [:show, :edit, :update, :destroy]


  def new
    @bibtex = Bibtex.new
  end

  def create
    myfile = File.new("#{Rails.root}/tmp/"+ bibtex_params[:name] + ".bib", "w")
    Reference.all.each do |r|
      myfile.write r.to_s
    end
    myfile.close
    send_file(
        "#{Rails.root}/tmp/"+ bibtex_params[:name] + ".bib",

    )
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bibtex
      @bibtex = Bibtex.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bibtex_params
      params.require(:bibtex).permit(:name)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bibtexes_helper.rb
module BibtexesHelper
end

app/helpers/booklets_helper.rb
module BookletsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/manuals_helper.rb
module ManualsHelper
end

app/helpers/miscs_helper.rb
module MiscsHelper
end

app/helpers/phdtheses_helper.rb
module PhdthesesHelper
end

app/views/bibtexes/_form.html.erb
<%= form_for(@bibtex) do |f| %>
  <% if @bibtex.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bibtex.errors.count, "error") %> prohibited this bibtex from being saved:</h2>

      <ul>
      <% @bibtex.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bibtexes/edit.html.erb
<h1>Editing Bibtex</h1>

<%= render 'form' %>

<%= link_to 'Show', @bibtex %> |
<%= link_to 'Back', bibtexes_path %>

app/views/bibtexes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bibtexes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bibtexes.each do |bibtex| %>
      <tr>
        <td><%= bibtex.name %></td>
        <td><%= link_to 'Show', bibtex %></td>
        <td><%= link_to 'Edit', edit_bibtex_path(bibtex) %></td>
        <td><%= link_to 'Destroy', bibtex, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bibtex', new_bibtex_path %>

app/views/bibtexes/new.html.erb
<h1>New Bibtex</h1>

<%= render 'form' %>

<%= link_to 'Back', references_path %>

app/views/bibtexes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bibtex.name %>
</p>

<%= link_to 'Edit', edit_bibtex_path(@bibtex) %> |
<%= link_to 'Back', bibtexes_path %>