config/routes.rb
Rails.application.routes.draw do
  resources :booklets
  resources :conferences
  resources :incollections
  resources :manuals
  resources :masterstheses
  resources :miscs
  resources :phdtheses
  resources :proceedings
  resources :techreports
  resources :unpuplisheds
  resources :bibtexes
  resources :inproceedings
  resources :books
  resources :articles
  resources :references

  root 'references#index'

end

app/models/article.rb
class Article < Reference
  validates :author, :journal, :volume, :title, :year, presence: true
end

app/models/bibtex.rb
class Bibtex < ActiveRecord::Base
end

app/models/book.rb
class Book < Reference
  validates :title, :year, :publisher, presence: true
end

app/models/booklet.rb
class Booklet < Reference
  validates :title, presence: true
end

app/models/conference.rb
class Conference < Reference
  validates :title, :year, :author, :booktitle, presence: true
end

app/models/incollection.rb
class Incollection < Reference
  validates :title, :publisher, :year, :author, :booktitle, presence: true
end

app/models/inproceeding.rb
class Inproceeding < Reference
  validates :title, :year, :author, :booktitle, presence: true
end

app/models/manual.rb
class Manual < Reference
  validates :title, presence: true
end

app/models/mastersthesis.rb
class Mastersthesis < Reference
  validates :author, :title, :school, :year, presence: true
end

app/models/misc.rb
class Misc < Reference
end

app/models/phdthesis.rb
class Phdthesis < Reference
  validates :author, :title, :school, :year, presence: true
end

app/models/proceeding.rb
class Proceeding < Reference
  validates :title, :year, presence: true
end

app/models/reference.rb
class Reference < ActiveRecord::Base

  def create_key
    key = self.author.partition(" ").first + self.year.to_s + self.title.partition(" ").first
    references = Reference.all
    abc = "abcdefghijklmnopqrstuvwxyz"
    abcIndex = 0
    while Reference.exists?(key: key)
        if abcIndex > 0 && abcIndex < abc.length
            key = key.chop
        end
        key = key + abc[abcIndex]
        if abcIndex < abc.length
            abcIndex = abcIndex + 1
        else
            abcIndex = 0
        end
    end
    self.key = key
  end

  def serialized_fields
    [:author, :title, :journal, :volume, :number, :month, :year, :pages, :publisher, :editor, :booktitle, :organization, :address, :note, :edition, :series, :annote, :chapter, :crossref, :howpublished, :institution, :school, :type] 
  end

  def to_s
    str = "@#{entry_type}{#{key},\n"
    serialized_fields.each do |field|
      str += "      #{field.to_s} = {#{self[field]}},\n" unless self[field].blank?
    end
    str += "}\n"
  end
end

app/models/techreport.rb
class Techreport < Reference
  validates :author, :title, :institution, :year, presence: true
end

app/models/unpuplished.rb
class Unpuplished < Reference
  validates :author, :title, :note, presence: true
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  before_action :set_reference, only: [:show, :edit, :update, :destroy]

  def index
    @references = Reference.paginate(:page => params[:page], :per_page => 20)
  end

  def show
  end

  def new
    @reference = Reference.new
  end

  def edit
  end

  def create
    @reference = Reference.new(reference_params)
    @reference.create_key

    respond_to do |format|
      if @reference.save
        format.html { redirect_to @reference, notice: 'Reference was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @reference.update(reference_params)
        format.html { redirect_to @reference, notice: 'Reference was successfully updated.' }
        format.json { render :show, status: :ok, location: @reference }
      else
        format.html { render :edit }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @reference.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Reference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def bibtex
    redirect_to "#{Rails.root}/app/views/references/download_bibtex.erb"
  end

  def download
    generate
    send_file(
        "#{Rails.root}/public/sigproc.bib",
        :disposition => 'attachment',
        :x_sendfile=>true
    )
  end

  def generate
    myfile = File.open("#{Rails.root}/public/sigproc.bib", "w")
    Reference.all.each do |r|
      myfile.write r.to_s
    end
    myfile.close
  end



  private

    def set_reference
      @reference = Reference.find(params[:id])
    end

      def reference_params
      params.require(:reference).permit(:key, :entry_type, :author, :title, :journal,
      :year, :volume, :number, :pages, :month, :note, :publisher, :series, :address, :edition,
      :booktitle, :editor, :organization, :annote, :chapter, :crossref, :howpublished, :institution, :school, :type)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bibtexes_helper.rb
module BibtexesHelper
end

app/helpers/booklets_helper.rb
module BookletsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/manuals_helper.rb
module ManualsHelper
end

app/helpers/miscs_helper.rb
module MiscsHelper
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/views/references/_form.html.erb
<%= form_for(@reference) do |f| %>
  <% if @reference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reference.errors.count, "error") %> prohibited this reference from being saved:</h2>

      <ul>
      <% @reference.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :key %><br>
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :entry_type %><br>
    <%= f.select :entry_type, options_for_select(@entry_type) %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_area :author %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :journal %><br>
    <%= f.text_area :journal %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :volume %><br>
    <%= f.number_field :volume %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :pages %><br>
    <%= f.text_field :pages %>
  </div>
  <div class="field">
    <%= f.label :month %><br>
    <%= f.number_field :month %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
</div><!--
  <div class="field">
    <%= f.label :publisher %><br>
    <%= f.text_area :publisher %>
  </div>
  <div class="field">
    <%= f.label :series %><br>
    <%= f.text_area :series %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :edition %><br>
    <%= f.text_area :edition %>
  </div>
  <div class="field">
    <%= f.label :booktitle %><br>
    <%= f.text_area :booktitle %>
  </div>
  <div class="field">
    <%= f.label :editor %><br>
    <%= f.text_area :editor %>
  </div>
  <div class="field">
    <%= f.label :organization %><br>
    <%= f.text_area :organization %>
</div>-->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/references/edit.html.erb
<h1>Editing Reference</h1>

<%= render 'form' %>

<%= link_to 'Show', @reference %> |
<%= link_to 'Back', references_path %>

app/views/references/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing References</h1>

<table>
  <thead>
    <tr>
      <th>Key</th>
      <th>Entry Type</th>
      <th>Author</th>
      <th>Title</th>
      <th>Journal</th>
      <th>Year</th>
      <th>Volume</th>
      <th>Number</th>
      <th>Pages</th>
      <th>Month</th>
      <th>Note</th>
      <th>Publisher</th>
      <th>Series</th>
      <th>Address</th>
      <th>Edition</th>
      <th>Booktitle</th>
      <th>Editor</th>
      <th>Organization</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @references.each do |reference| %>
      <tr>
        <td><%= link_to reference.key, reference %></td>
        <td><%= reference.entry_type %></td>
        <td><%= reference.author %></td>
        <td><%= reference.title %></td>
        <td><%= reference.journal %></td>
        <td><%= reference.year %></td>
        <td><%= reference.volume %></td>
        <td><%= reference.number %></td>
        <td><%= reference.pages %></td>
        <td><%= reference.month %></td>
        <td><%= reference.note %></td>
        <td><%= reference.publisher %></td>
        <td><%= reference.series %></td>
        <td><%= reference.address %></td>
        <td><%= reference.edition %></td>
        <td><%= reference.booktitle %></td>
        <td><%= reference.editor %></td>
        <td><%= reference.organization %></td>
        <td><%= link_to 'Show', reference %></td>
        <!-- <td><%= link_to 'Edit', edit_reference_path(reference) %></td> -->
        <td><%= link_to 'Destroy', reference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p> <%= will_paginate @references %> </p>

<%= link_to 'Download Bibtex File', new_bibtex_path %>
<%= link_to 'New Article', new_article_path %>
<%= link_to 'New Book', new_book_path %>
<%= link_to 'New Booklet', new_booklet_path %>
<%= link_to 'New Conference', new_conference_path %>
<%= link_to 'New Incollection', new_incollection_path %>
<%= link_to 'New Inproceeding', new_inproceeding_path %>
<%= link_to 'New Manual', new_manual_path %>
<%= link_to 'New Masters thesis', new_mastersthesis_path %>
<%= link_to 'New misc', new_misc_path %>
<%= link_to 'New Ph.D. thesis', new_phdthesis_path %>
<%= link_to 'New Proceeding', new_proceeding_path %>
<%= link_to 'New Techreport', new_techreport_path %>
<%= link_to 'New Unpublished', new_unpuplished_path %>

app/views/references/new.html.erb
<h1>New Reference</h1>

<%= render 'form' %>

<%= link_to 'Back', references_path %>

app/views/references/new_article.erb
<%= form_for(@reference) do |f| %>
  <% if @reference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reference.errors.count, "error") %> prohibited this reference from being saved:</h2>

      <ul>
      <% @reference.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1>New <%= @entry_type %></h1>
  <strong>An article from a journal or magazine</strong>
  <%= f.hidden_field :entry_type, :value => @entry_type %>

  <h3>Required fields</h3>

  <div class="field">
    <%= f.label :key %><br>
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_area :author %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :journal %><br>
    <%= f.text_area :journal %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :volume %><br>
    <%= f.number_field :volume %>
  </div>

  <h3>Optional fields</h3>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :pages %><br>
    <%= f.text_field :pages %>
  </div>
  <div class="field">
    <%= f.label :month %><br>
    <%= f.number_field :month %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/references/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Key:</strong>
  <%= @reference.key %>
</p>

<p>
  <strong>Author:</strong>
  <%= @reference.author %>
</p>

<p>
  <strong>Title:</strong>
  <%= @reference.title %>
</p>

<p>
  <strong>Journal:</strong>
  <%= @reference.journal %>
</p>

<p>
  <strong>Year:</strong>
  <%= @reference.year %>
</p>

<p>
  <strong>Volume:</strong>
  <%= @reference.volume %>
</p>

<p>
  <strong>Number:</strong>
  <%= @reference.number %>
</p>

<p>
  <strong>Pages:</strong>
  <%= @reference.pages %>
</p>

<p>
  <strong>Month:</strong>
  <%= @reference.month %>
</p>

<p>
  <strong>Note:</strong>
  <%= @reference.note %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @reference.publisher %>
</p>

<p>
  <strong>Series:</strong>
  <%= @reference.series %>
</p>

<p>
  <strong>Address:</strong>
  <%= @reference.address %>
</p>

<p>
  <strong>Edition:</strong>
  <%= @reference.edition %>
</p>

<p>
  <strong>Booktitle:</strong>
  <%= @reference.booktitle %>
</p>

<p>
  <strong>Editor:</strong>
  <%= @reference.editor %>
</p>

<p>
  <strong>Organization:</strong>
  <%= @reference.organization %>
</p>

<p>
  <strong>Entry type:</strong>
  <%= @reference.entry_type %>
</p>

<p>
  <strong>Annote:</strong>
  <%= @reference.annote %>
</p>

<p>
  <strong>Chapter:</strong>
  <%= @reference.chapter %>
</p>

<p>
  <strong>Crossref:</strong>
  <%= @reference.crossref %>
</p>

<p>
  <strong>Howpublished:</strong>
  <%= @reference.howpublished %>
</p>

<p>
  <strong>Institution:</strong>
  <%= @reference.institution %>
</p>

<p>
  <strong>School:</strong>
  <%= @reference.school %>
</p>


<%= link_to 'Back', references_path %>